### ISSUE TITLE
Dynamics Of GTAD+PGCN :

### ISSUE THREAD

**Issue by lakshaymehra** [frostinassiky/gtad#8]
Hi,
Thank you for this amazing paper and wonderful repository!
While reading the paper, I found that GTAD+PGCN combined model achieves much better results than any other model trained on THUMOS'14.
I have my own data set and would like to use the combined GTAD + PGCN model for training. 

1. From what I understand, the combined model uses extracted features from RGB and Flow frames using a TSN or I3D Feature Extractor (and stored as HDF5 files), GTAD is used to generate proposals, and then the proposals are passed into the PGCN architecture. Is that right ?

2. If my logic above in point 1 is correct, how can I only use the GTAD repo for generating proposals? Can you guide me through how I can train the combined GTAD + PGCN model on my own data set ?

**Comment by frostinassiky** [comment]
Dear @lakshaymehra ,

Thanks for your interests. Using GTAD+PGCN can reach a better performance. 
1. Your logic is correct. However, PGCN models (rgb+flow) are provided in their repo. We didn't train them. We use PGCN models to re-score our G-TAD detections. Since you have your own dataset, you have to **train PGCN models by yourself**.
2. The `gtad_inference.py` script will produce the action predictions under a `results` folder. You can load those results in P-GCN dataset.

**Comment by lakshaymehra** [comment]
@Frostinassiky Thanks a lot for the detailed response!

**Comment by semchan** [comment]
> Dear @lakshaymehra ,
> 
> Thanks for your interests. Using GTAD+PGCN can reach a better performance.
> 
>     1. Your logic is correct. However, PGCN models (rgb+flow) are provided in their repo. We didn't train them. We use PGCN models to re-score our G-TAD detections. Since you have your own dataset, you have to **train PGCN models by yourself**.
> 
>     2. The `gtad_inference.py` script will produce the action predictions under a `results` folder. You can load those results in P-GCN dataset.

hi, could you please tell me more detail of how to load the results into P-GCN? thanks very much
